[env:uno]
platform = atmelavr
board = uno
framework = arduino

upload_protocol = arduino
upload_port = COM4

monitor_speed = 9600

lib_deps =
    fastled/FastLED@3.5.0
    arduino-libraries/Servo
    z3t0/IRremote
    electroniccats/MPU6050